version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-scheduler"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "EnvVar=\"env_var\""
image_repositories = []
